import time

start = input('Press any button to start:')

print('Twoey: Hello! I am the spirit of Twoey.')
time.sleep(1)
print('Fivey: Hello. I am the spirit of Fivey.')
time.sleep(1)
print('Fivey: You are currently in an abandoned military base 40 meters underground.')
time.sleep(1)
print('Twoey: Glad you\'re finally awake. Unfortunately, ever since you got hit by Colossalis...')
time.sleep(2)
print('Fivey: The monsters took over without you.')
time.sleep(2)
print('Twoey: But don\'t worry! We are here to help you destroy these horrid monsters!')
time.sleep(1)
print('Twoey: Now for your first decision: Do you take iron armour?')
print('Fivey: Or an iron sword?')
time.sleep(1)
thebeginning = input('Game: Do you listen to Fivey(f) or Twoey(t)?: ')
if thebeginning == 'f'.lower():
    time.sleep(1)
    print('Fivey: Good idea. You will be able to defend yourself.')
    print('Game: You gained an iron sword!')
else:
    time.sleep(1)
    print('Twoey: Great idea! You can absorb damage now.')
    print('Game: You gained iron armour!')
time.sleep(3)
print('Fivey: Ok. Let\'s head to the surface.')
time.sleep(2)
print('Twoey: Wait!')
time.sleep(1)
print('Fivey: ?')
time.sleep(1)
print('Twoey: I think we should search the base. See if anyone left more loot.')
name = input('Fivey: No... Wait, what\'s you\'re name?: ')
print('Fivey: Alright. I think ', name, 'is plenty ready.')
time.sleep(1)
print('Twoey: It\'s up to you, ', name, '. Do you go to the surface (Fivey\'s choice) or search the base?(My choice)?')
twoeyorfivey = input('Game: Do you listen to Twoey(t) or Fivey(f)?: ')
if twoeyorfivey.lower() == 't':
    print('Twoey: Good.')
    time.sleep(1)
    print('Game: 1 hour later...')
    time.sleep(2)
    print('Twoey: Hey, look! The storage room!')
    time.sleep(1)
    print('Fivey: Bet you we can find some stuff here!')
    time.sleep(2)
    print('Game: You got a Health Potion!')
    time.sleep(1)
    if thebeginning.lower() == 'f':
        print('Game: You got iron armour!')
    else:
        print('Game: You got an iron sword!')
print('Fivey: Alright then, let\'s head out.')
time.sleep(5)
print('Twoey: The surface is a lot more destroyed than I remember...')
time.sleep(1)
print('Fivey: Probally Colossalis. Get used to it.')
time.sleep(1)
print('Twoey: Ok, let\'s get moving. I vote North.')
